[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_program = "35ffyyPoc4mjdyaApeqySnLygqXGvfi1PJxNc5NaLKPx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
