[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_program = "8akcs6EFZN1KQCkVNQoswS1UpaTs2mxKEfF2L4nui57A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tarunjaiswal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
